timezone: America/Los_Angeles
encoding: utf-8

author: Shane
site_name: Open Links in New Tab
site_url: https://open-links-in-new-tab.cssnr.com

github_name: cssnr/open-links-in-new-tab
github_url: https://github.com/cssnr/open-links-in-new-tab

chrome_id: efahmjakjnnmleokcaomicgfhobabdkc
chrome_url: https://chromewebstore.google.com/detail/open-links-in-new-tab/efahmjakjnnmleokcaomicgfhobabdkc

firefox_id: open-links-in-new-tab
firefox_url: https://addons.mozilla.org/addon/open-links-in-new-tab

discord_webhook: https://discord.com/api/webhooks/242137648028712961/4xM7SXClH_i8we_epG6AXMaqhueg5L5oAVf1dnLw1_el05OxZ-JVfph-QrcQwPkOMJem
