timezone: America/Los_Angeles
encoding: utf-8

url: https://open-links-in-new-tab.cssnr.com

author: Shane
site_name: Open Links in New Tab

menu:
    - name: Home
      link: /
    - name: Documentation
      link: /docs/
    - name: Screen Shots
      link: /screenshots/

github_name: cssnr/open-links-in-new-tab
github_url: https://github.com/cssnr/open-links-in-new-tab

chrome_id: efahmjakjnnmleokcaomicgfhobabdkc
chrome_url: https://chromewebstore.google.com/detail/open-links-in-new-tab/efahmjakjnnmleokcaomicgfhobabdkc

firefox_id: open-links-in-new-tab
firefox_url: https://addons.mozilla.org/addon/open-links-in-new-tab

discord_server: 899171661457293343
discord_invite: https://discord.gg/wXy6m2X8wY

feedback_link: https://cssnr.github.io/feedback/?app=Open%20Links%20in%20New%20Tab
relay_url: https://relay.cssnr.com/discord/1258944618389569566
