timezone: America/Los_Angeles
encoding: utf-8

url: https://open-links-in-new-tab.cssnr.com

author: Shane
site_name: Open Links in New Tab

github_name: cssnr/open-links-in-new-tab
github_url: https://github.com/cssnr/open-links-in-new-tab

chrome_id: efahmjakjnnmleokcaomicgfhobabdkc
chrome_url: https://chromewebstore.google.com/detail/open-links-in-new-tab/efahmjakjnnmleokcaomicgfhobabdkc

firefox_id: open-links-in-new-tab
firefox_url: https://addons.mozilla.org/addon/open-links-in-new-tab

discord_invite: https://discord.gg/wXy6m2X8wY
discord_webhook: https://discord.com/api/webhooks/1258944618389569566/gqge0T5UZcJHLxfAFLPNjlzsuqikQJtTlCRvVWbw2ufDv_WrJ8yzVRWenb__s1PxyawH
